routes/web.php
<?php

Route::prefix('admin')->group(function() {
	Route::get('/', 'Admin\ProductController@index')->name('admin');

	Route::name('product.')->prefix('product')->group(function() {
		Route::get('/', 'Admin\ProductController@index')->name('index');
		Route::get('/show/{id}', 'Admin\ProductController@show')->name('show');
		Route::get('/create', 'Admin\ProductController@create')->name('create');
		Route::post('/store', 'Admin\ProductController@store')->name('store');
		Route::get('/edit/{id}', 'Admin\ProductController@edit')->name('edit');
		Route::post('/update/{id}', 'Admin\ProductController@update')->name('update');
		Route::get('/destroy/{id}', 'Admin\ProductController@destroy')->name('destroy');
	});

	Route::name('category.')->prefix('category')->group(function() {
		Route::get('/', 'Admin\CategoryController@index')->name('index');
		Route::get('/show/{id}', 'Admin\CategoryController@show')->name('show');
		Route::get('/create', 'Admin\CategoryController@create')->name('create');
		Route::post('/store', 'Admin\CategoryController@store')->name('store');
		Route::get('/edit/{id}', 'Admin\CategoryController@edit')->name('edit');
		Route::post('/update/{id}', 'Admin\CategoryController@update')->name('update');
		Route::get('/destroy/{id}', 'Admin\CategoryController@destroy')->name('destroy');
	});

	Route::name('customer.')->prefix('customer')->group(function() {
		Route::get('/', 'Admin\CustomerController@index')->name('index');
		Route::get('/show/{id}', 'Admin\CustomerController@show')->name('show');
		Route::get('/destroy/{id}', 'Admin\CustomerController@destroy')->name('destroy');
	});

	Route::name('order.')->prefix('order')->group(function() {
		Route::get('/', 'Admin\OrderController@index')->name('index');
		Route::get('/show/{id}', 'Admin\OrderController@show')->name('show');
		Route::get('/edit/{id}', 'Admin\OrderController@edit')->name('edit');
		Route::post('/update/{id}', 'Admin\OrderController@update')->name('update');
		Route::get('/destroy/{id}', 'Admin\OrderController@destroy')->name('destroy');
	});

	Route::name('user.')->prefix('user')->group(function() {
		Route::get('/', 'Admin\UserController@index')->name('index');
		Route::get('/show/{id}', 'Admin\UserController@show')->name('show');
		Route::get('/edit/{id}', 'Admin\UserController@edit')->name('edit');
		Route::post('/update/{id}', 'Admin\UserController@update')->name('update');
		Route::get('/destroy/{id}', 'Admin\UserController@destroy')->name('destroy');
	});

	Route::name('role.')->prefix('role')->group(function() {
		Route::get('/', 'Admin\RoleController@index')->name('index');
		Route::get('/show/{id}', 'Admin\RoleController@show')->name('show');
		Route::get('/create', 'Admin\RoleController@create')->name('create');
		Route::post('/store', 'Admin\RoleController@store')->name('store');
		Route::get('/edit/{id}', 'Admin\RoleController@edit')->name('edit');
		Route::post('/update/{id}', 'Admin\RoleController@update')->name('update');
		Route::get('/destroy/{id}', 'Admin\RoleController@destroy')->name('destroy');
	});

	Route::name('slider.')->prefix('slider')->group(function() {
		Route::get('/', 'Admin\SliderController@index')->name('index');
		Route::get('/show/{id}', 'Admin\SliderController@show')->name('show');
		Route::get('/create', 'Admin\SliderController@create')->name('create');
		Route::post('/store', 'Admin\SliderController@store')->name('store');
		Route::get('/edit/{id}', 'Admin\SliderController@edit')->name('edit');
		Route::post('/update/{id}', 'Admin\SliderController@update')->name('update');
		Route::get('/destroy/{id}', 'Admin\SliderController@destroy')->name('destroy');
	});

	Route::name('slide.')->prefix('slide')->group(function() {
		Route::get('/', 'Admin\SlideController@index')->name('index');
		Route::get('/show/{id}', 'Admin\SlideController@show')->name('show');
		Route::get('/create', 'Admin\SlideController@create')->name('create');
		Route::post('/store', 'Admin\SlideController@store')->name('store');
		Route::get('/edit/{id}', 'Admin\SlideController@edit')->name('edit');
		Route::post('/update/{id}', 'Admin\SlideController@update')->name('update');
		Route::get('/destroy/{id}', 'Admin\SlideController@destroy')->name('destroy');
	});

	Route::name('carts.')->prefix('carts')->group(function() {
		Route::get('/', 'Admin\CartController@index')->name('index');
	});

	Route::name('contacts.')->prefix('contacts')->group(function() {
		Route::get('/', 'Admin\ContactController@index')->name('index');
		Route::get('/destroy/{id}', 'Admin\ContactController@destroy')->name('destroy');
	});

	Route::name('admin.')->group(function() {
		Route::get('login','Admin\AuthController@showLoginForm')->name('login');
		Route::post('login','Admin\AuthController@login');
		Route::get('register','Admin\AuthController@showRegistrationForm')->name('register');
		Route::post('register','Admin\AuthController@register');
		Route::post('logout','Admin\AuthController@logout')->name('logout');
	});
});

Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('home');

Route::name('store.')->prefix('store')->group(function() {
	Route::get('/', 'HomeController@store')->name('index');
	Route::get('/{id}', 'HomeController@category')->name('id');
});

Route::name('filter.')->prefix('filter')->group(function() {
	Route::post('/', 'HomeController@filter')->name('index');
});

Route::name('page.')->prefix('page')->group(function() {
	Route::get('/', 'HomeController@filter')->name('index');
	Route::get('?page={page}', 'HomeController@filter')->name('page');
});

Route::get('product/{id}', 'HomeController@product')->name('product');

Route::name('cart.')->prefix('cart')->group(function() {
	Route::get('/', 'CartController@index')->name('index');
	Route::put('add', 'CartController@add')->name('add');
	Route::patch('update', 'CartController@update')->name('update');
	Route::delete('delete', 'CartController@delete')->name('delete');
});

Route::get('search', 'HomeController@search')->name('search');

Route::name('contact.')->prefix('contact')->group(function() {
	Route::get('/', 'ContactController@index')->name('index');
	Route::post('/send', 'ContactController@sendMail')->middleware('verified')->name('sendmail');
});

Route::name('checkout.')->prefix('checkout')->group(function() {
	Route::get('/', 'CheckOutController@index')->name('index');
	Route::post('checkout', 'CheckOutController@checkout')->name('checkout');
});

resources/views/includes/admin/footer.blade.php
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>

</div>
<!-- ./wrapper -->
<script src="{{asset('js/bootstrap.min.js')}}"></script>
<script src="{{asset('js/dist/adminlte.min.js')}}"></script>
<script>
  $(function () {
    $('#table').DataTable({
      'paging'      : true,
      'lengthChange': true,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : true
    })
  })
</script>

</body>
</html>

resources/views/includes/admin/head.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Admin | @yield('title')</title>
  <meta name="_token" content="{{csrf_token()}}" />
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="stylesheet" href="{{asset('css/bootstrap/dist/css/bootstrap.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/font-awesome/css/font-awesome.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/Ionicons/css/ionicons.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/dist/AdminLTE.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/admin.css')}}">
  <link rel="stylesheet" href="{{asset('css/dist/skins/_all-skins.min.css')}}">
  <link rel="stylesheet" href="{{asset('css/dataTables.bootstrap.min.css')}}">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <script src="{{asset('js/jquery.min.js')}}"></script>
  <script src="{{asset('js/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('js/dataTables.bootstrap.min.js')}}"></script>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

resources/views/includes/admin/header.blade.php
<header class="main-header">
    <a href="{{ Route('product.index') }}" class="logo">
      @yield('title')
    </a>
    <nav class="navbar navbar-static-top">
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          @if(Auth::guest())
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.login') }}">{{ __('Login') }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ route('admin.register') }}">{{ __('Register') }}</a>
            </li>
          @else
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="hidden-xs">{{ Auth::guard('admin')->user()->name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="{{ Route('user.show', Auth::guard('admin')->user()->id) }}" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{{ Route('admin.logout') }}" class="btn btn-default btn-flat"
                     onclick="event.preventDefault();
                                   document.getElementById('logout-form').submit();">
                      {{ __('Sign out') }}
                  </a>

                  <form id="logout-form" action="{{ Route('admin.logout') }}" method="POST" style="display: none;">
                      @csrf
                  </form>
                </div>
              </li>
            </ul>
          </li>
          @endif
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

resources/views/includes/admin/noti.blade.php
@if(session('success'))
	<div class="alert alert-success alert-block">
		<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ session('success') }}</strong>
	</div>
@endif
@if(session('fail'))
	<div class="alert alert-danger alert-block">
		<button type="button" class="close" data-dismiss="alert">×</button>	
        <strong>{{ session('fail') }}</strong>
	</div>
@endif

resources/views/includes/admin/sidebar.blade.php
 <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="treeview side0">
          <a>
            <span>Categories</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('category.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
            @can('categories.create')
              <li><a href="{{ Route('category.create') }}"><i class="fas fa-plus-circle"></i> Add</a></li>
            @endcan
          </ul>
        </li>

        <li class="treeview side1">
          <a>
            <span>Products</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('product.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
            @can('products.create')
              <li><a href="{{ Route('product.create') }}"><i class="fas fa-plus-circle"></i> Add</a></li>
            @endcan
          </ul>
        </li>

        <li class="treeview side2">
          <a>
            <span>Customers</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('customer.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
          </ul>
        </li>

        <li class="treeview side9">
          <a>
            <span>Contacts</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('contacts.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
          </ul>
        </li>

        <li class="treeview side8">
          <a>
            <span>Carts</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('carts.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
          </ul>
        </li>

        <li class="treeview side3">
          <a>
            <span>Orders</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('order.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
          </ul>
        </li>

        <li class="treeview side4">
          <a>
            <span>Users</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('user.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
          </ul>
        </li>

        <li class="treeview side5">
          <a>
            <span>Roles</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('role.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
            @can('roles.create')
              <li><a href="{{ Route('role.create') }}"><i class="fas fa-plus-circle"></i> Add</a></li>
            @endcan
          </ul>
        </li>

        <li class="treeview side6">
          <a>
            <span>Sliders</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('slider.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
            @can('sliders.create')
              <li><a href="{{ Route('slider.create') }}"><i class="fas fa-plus-circle"></i> Add</a></li>
            @endcan
          </ul>
        </li>

        <li class="treeview side7">
          <a>
            <span>Slides</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="{{ Route('slide.index') }}"><i class="fas fa-list-alt"></i> List</a></li>
            @can('slides.create')
              <li><a href="{{ Route('slide.create') }}"><i class="fas fa-plus-circle"></i> Add</a></li>
            @endcan
          </ul>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>